// <auto-generated />
namespace Lab6_b2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class _class : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_class));
        
        string IMigrationMetadata.Id
        {
            get { return "202304021421159_class"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
